hhaccessibility/hhaccessibility.github.io

importers/toiletfinder.com/download_html.py, importers/toiletfinder.com/generate_csv.py, importers/toiletfinder.com/html_scraper.py, importers/toiletfinder.com/model/toilet.py
- Included most visited venues to get more venue data
- Also, scraped, propogated, and exported thumbnail and venue article URL's
=> Issue 1 improvements

db/create_tables.sql
=> db: added script to create tables in mysql

db/create_tables.sql
=> db: added unique constraint to user's username field

app/database/seeds/data/building_tag.json
=> app: fixed description for Healthcare tag

app/resources/assets/sass/app.scss, app/resources/views/pages/privacy_policy.blade.php, app/resources/views/pages/signup.blade.php, app/resources/views/pages/terms_of_use.blade.php, app/routes/web.php
=> app: made sign up page look more like mockup

app/app/Http/Controllers/MyLoginController.php, app/app/Http/Controllers/ProfileController.php, app/app/Http/Controllers/SignUpController.php, app/database/migrations/2016_10_30_053317_create_initial_database_schema.php, app/database/seeds/UserTableSeeder.php, app/resources/assets/sass/app.scss, app/resources/views/pages/login.blade.php, app/resources/views/pages/profile.blade.php, app/resources/views/pages/signup.blade.php, app/routes/web.php
- Removed username from login form, MyLoginController
- Added logout feature as a link on the profile view
- Replaced username 'test' with email 'josh.greig@gmail.com'
- Improved colour of placeholder text in sign up form
=> app: added SignUpController and removed username from user table

app/resources/assets/sass/app.scss, app/resources/views/includes/head.blade.php
Areeba suggested the font and it seemed like a simple improvement to try.
=> app: switched from arial to Didact Gothic font family

app/config/app.php, app/resources/views/includes/head.blade.php, app/resources/views/includes/header.blade.php, app/resources/views/pages/home.blade.php, app/resources/views/pages/login.blade.php, app/resources/views/pages/signup/form.blade.php
=> app: renamed Access Locator to AccessLocator as in removed the space

app/resources/views/pages/home.blade.php
=> renamed login to sign in on home page

app/resources/assets/sass/app.scss, app/resources/views/pages/home.blade.php
=> app: home: made the Sign in / Sign up text bold

app/app/BaseUser.php, app/resources/views/pages/signup/success.blade.php
=> app: fixed some log in/sign in consistency mistakes

app/resources/assets/sass/app.scss, app/resources/views/pages/home.blade.php
=> app: home page updated with slogan

app/resources/views/pages/location_search/search.blade.php
=> app: added search view file

app/app/Http/Controllers/LocationSearchController.php, app/public/js/location_search_map.js, app/resources/assets/sass/app.scss, app/resources/views/pages/location_search/map.blade.php, app/resources/views/pages/location_search/search.blade.php
=> app: added Google Map and markers for various locations

app/public/js/location_search_map.js
=> app: made location search markers clickable

app/app/BaseUser.php, app/app/Http/Controllers/LocationSearchController.php
=> filtered locations down to the search radius

app/resources/views/pages/location_search/spreadsheet.blade.php
=> app: renamed Rating to Accessibility Rating %

app/database/migrations/2016_10_30_053317_create_initial_database_schema.php, app/database/seeds/DatabaseSeeder.php
=> app: added new region table and seeding for it

app/app/Http/Controllers/SignUpController.php, app/resources/views/pages/signup/success.blade.php
=> app: improved clarity of user sign up messages

app/database/seeds/data/location_location_tag.json
=> app: location_location_tag.json removed references to removed locations

app/database/seeds/data/faq_item.json
=> app: fixed grammatical errors

app/public/js/profile.js
=> app: profile adjusted to always use a new profile photo URL

app/resources/assets/sass/app.scss, app/resources/views/includes/header.blade.php, app/resources/views/pages/our_vision.blade.php, app/routes/web.php
=> app: removed our vision page

app/database/seeds/data/location.json, app/database/seeds/data/location_duplicate.json, app/database/seeds/data/location_location_tag.json
Also, added id's to a few location_duplicate records that came from
OpenStreetMap.
=> location.json: removed a couple duplicates of Bruce Park

app/app/Http/Controllers/LocationRatingController.php
=> location rating: checked signed in status in api

app/public/js/profile.js, app/resources/views/pages/profile/profile.blade.php
I have tested it, it will uncheck all.
=> fix uncheckall feature in profile page Related to issue #317

app/public/js/hover_text.js, app/resources/assets/sass/app.scss, app/resources/views/pages/home.blade.php
=> began making a text hover feature

app/resources/assets/sass/_home.scss
This looked better.
Related to #242
=> _home.scss: made background semitransparent with 70% opacity

app/app/BaseUser.php
This was based on a comment from Stephanos when he tested the feature.
Related to #204
=> BaseUser.php: corrected spelling mistakes in sendVerificationEmail

app/resources/views/includes/header.blade.php
=> added Sign out title to sign out menu item

app/app/Http/Controllers/PasswordRecoveryController.php, app/app/Http/Controllers/SignInController.php, app/resources/assets/sass/_sign_in.scss, app/resources/views/pages/signin.blade.php
Also, modified PasswordRecoveryController to redirect to the signin page
and show the Password Changed message.
Also, updated SCSS and the signin.blade.php view to show the specified
message.
Related to #369
=> app: sign in: modified SignInController to show a specified message

app/public/js/home.js
Added a functionality to change the current location on a map to the location clicked by the user.
=> Modified home.js to set the marker to a clicked location on map

app/app/Http/Controllers/LocationRatingController.php, app/app/Http/Controllers/LocationReportController.php, app/app/Http/Controllers/ProfileController.php
This includes location rating, report, and user profile.
This also includes some navigation updates so that 'Next' and 'Submit'
buttons in the rating feature stay consistent with the new order of
question categories.
Done as part of #244
=> Question Category sorted on various pages

app/app/Http/Controllers/LocationSearchController.php
=> app: improved sorting of locations by distance and rating

app/database/migrations/2017_11_25_122800_add_icon_to_location_tag.php, app/database/seeds/data/location_tag.json, app/public/js/location_report.js, app/resources/assets/sass/_location_map_report.scss, app/resources/assets/sass/app.scss, app/resources/views/pages/location_report/collapsed.blade.php, importers/utils/json_to_db.py, importers/utils/sync/sync.py
This included a migration to add the icon_selector field to the
location_tag table.
This also included some changes to the json_to_db tool to merge the new
icon information into deployed databases.
This also included some JavaScript and SCSS changes to choose the icon
layout when the viewport width and number of location tags suggest that
the icons will fit better.
Related to #430
=> app: added location tag icons when they fit better than full text

app/app/BaseUser.php, app/app/Http/Controllers/LocationReportController.php, app/app/Http/Controllers/LocationSearchController.php, app/public/js/location_report.js, app/resources/assets/sass/_location_map_report.scss, app/resources/assets/sass/_location_report.scss, app/resources/views/pages/location_report/top.blade.php
Also, made the location title adjust font size based on width of viewport.
Also, wrapped the Universal/Personal buttons to new row at narrow viewport
widths.
Related to #249
=> app: added back to location search button from location map view

app/app/Http/Controllers/DuplicateLocationFinderController.php, app/app/Http/Controllers/LocationSearchController.php, app/database/seeds/data/location.json, app/database/seeds/data/location_duplicate.json, app/database/seeds/data/location_location_tag.json, app/resources/assets/sass/_duplicate_location_finder.scss, app/resources/assets/sass/_location_map_report.scss, app/resources/assets/sass/app.scss, app/resources/views/pages/internal_features/duplicate_finder.blade.php, app/resources/views/pages/location_report/collapsed.blade.php, app/routes/web.php
Also, removed some duplicated locations found with the new tool.
A few street intersections were removed too since we don't want to rate
them.
=> app: added a duplicate location finder tool for internal users

app/app/libraries/Gis.php
I forgot to add this Gis library to another commit and broke the location
search functionality at app.accesslocator.com.
This commit fixes the mistake.
=> app: added Gis library

app/app/Libraries/Gis.php
This fixed a problem in Ubuntu which is case sensitive and wasn't looking
for the file in the intended way.
=> app: renamed libraries to Libraries

app/resources/assets/sass/_location_map_report.scss
Hello Josh, please review my Pull Request
=> Mi Sook's first try

app/resources/views/pages/profile/profile.blade.php
This fixes a bug that Yashankit caught.
Related to #451
=> app: profile: fixed bug where province wasn't saving on profile

app/app/Http/Controllers/LocationManagementController.php, app/app/Http/Controllers/ProfileController.php, app/resources/assets/sass/_locations_added_by_me.scss, app/resources/assets/sass/_placeholders.scss, app/resources/assets/sass/_reviewed_locations.scss, app/resources/assets/sass/app.scss, app/resources/views/pages/location_management/locations_added_by_me.blade.php, app/resources/views/pages/location_rating/reviewed_locations.blade.php, app/resources/views/pages/profile/profile.blade.php, app/routes/web.php
=> app: added user's list of added locations and a location delete feature

app/app/BaseUser.php, app/app/Http/Controllers/LocationSearchController.php, app/public/js/location_search_map.js, app/public/js/utils.js
Also, enforced limit of 500km for location search radius
Related to #373
=> app: fixed race condition when adjusting center of the circle

app/resources/views/pages/location_management/locations_added_by_me.blade.php
This is in response to feedback from Blandine on #454.
Blandine commented, "Change "Locations Added By Me" to "Added Locations"".
=> app: reworded title of My Added Locations page

app/public/js/location_search_map.js
=> now circle is always editable related #373

app/app/Http/Controllers/InternalFeaturesController.php, app/resources/views/pages/internal_features/user_report.blade.php, app/resources/views/pages/location_rating/rate.blade.php, app/routes/web.php
This feature is intended to help Blandine demo the application to people.
She was having trouble signing into the application and wants to show the
signup process.  The signup process doesn't work for email addresses
already signed up, though.
This feature is restricted to just Blandine's email addresses for now to
prevent loss of important answer data and abuse.
=> app: added a feature to delete users

app/app/BaseUser.php
This fixes a bug that was recently merged.
=> app: fixed bug where private method was called from another class

app/database/migrations/2018_02_04_140000_add_question_order_field.php
I forgot to add/commit this file in an earlier pull request.
Related to #489
=> db: added migration for new order field

app/public/js/home.js, app/public/js/utils.js, app/resources/assets/sass/_dialogs.scss, app/resources/assets/sass/app.scss
=> app: added a dialog to clear up the redirection process to the end user

app/public/js/home.js
of the redirect
Also, used pushState to reset the URL immediately upon loading the HTTPS
version.
Related to #522
=> app: finished the redirect and setting the geolocation upon completion

app/resources/views/pages/location_management/locations_added_by_me.blade.php
Blandine and I thought this looked cleaner.
Related to #521
=> app: locations-added-by-me: replaced + with a plus circle icon

app/app/Http/Controllers/QuestionExplanationController.php, app/app/UuidTrait.php, app/public/js/location_rating.js, app/public/js/profile.js, app/public/js/question_explanation.js, app/public/js/utils.js, app/resources/assets/sass/_dialogs.scss, app/resources/assets/sass/_location_map_report.scss, app/resources/assets/sass/_location_question_category_view_and_rating.scss, app/resources/assets/sass/_question_explanation.scss, app/resources/assets/sass/_question_explanation_link.scss, app/resources/assets/sass/app.scss, app/resources/views/pages/components/question_explanation_link.blade.php, app/resources/views/pages/location_rating/questions.blade.php, app/resources/views/pages/location_rating/rate.blade.php, app/resources/views/pages/location_report/question_category_report.blade.php, app/resources/views/pages/location_report/questions.blade.php, app/resources/views/pages/profile/profile.blade.php, app/resources/views/pages/questions/question_explanation.blade.php, app/resources/views/pages/questions/question_explanation_dialog_content.blade.php, app/routes/web.php
Also, made the question explanation appear in a dialog when the user
doesn't use a screen reader.
Related to #506
=> app: added question explanation to view and profile

app/app/Http/Controllers/LocationReportController.php, app/resources/assets/sass/_location_map_report.scss, app/resources/views/pages/location_report/collapsed.blade.php, app/resources/views/pages/location_report/top.blade.php
=> app: added rating counts and a comments link to the location map report

app/resources/views/pages/location_management/add_new_location.blade.php
=> app: moved Other to the bottom of the location group list

app/app/BaseUser.php
=> app: fixed bug in email confirmation

app/app/Providers/RouteServiceProvider.php, app/routes/auth.php, app/routes/contact.php, app/routes/internal_features.php, app/routes/location.php, app/routes/password_recovery.php, app/routes/profile.php, app/routes/questions.php, app/routes/ratings.php, app/routes/web.php
For better routes readability I split the web routes files into subfiles.
=> Splitted web.php

importers/utils/import_helpers/env_loader.py, importers/utils/import_helpers/rating_cache_task_loader.py
This fixes a mistake from an earlier pull request where I forgot to
commit these files.
Related to #555
=> importers: utils: added overlooked files for update_rating_cache.py

app/app/Image.php, app/database/migrations/2018_06_17_002542_create_image_table.php
=> app: adjusted Image table to use a GUID for primary key

app/.gitignore, app/resources/assets/sass/_location_management.scss
Fixed the compiled CSS validation and added public/fonts in .gitignore to ignore this files.
=> Fixed compiled css validation

app/app/Libraries/Emailer.php
=> app: replaced hardcoded references with .env references

app/resources/assets/sass/_home.scss, app/resources/views/pages/home.blade.php
=> issues #567

app/app/BaseUser.php, app/app/Http/Controllers/ContactController.php, app/app/Http/Controllers/PasswordRecoveryController.php, app/app/Http/Controllers/SignUpController.php, app/app/Mail/ConfirmationMail.php, app/app/Mail/ContactMail.php, app/app/Mail/RecoveryPasswordMail.php, app/composer.json, app/config/app.php, app/config/mail.php, app/resources/views/mails/confirmation.blade.php, app/resources/views/mails/contact.blade.php, app/resources/views/mails/password_recovery.blade.php
@joshi1983 I think you merged my code into your issue-520 not in master so I request you to merge this into master.
=> Merge Email Fix Code into Master

app/tests/HomeTest.php
=> app: HomeTest.php fixed

app/app/Http/Controllers/HomeController.php, app/resources/assets/sass/_location_search_table.scss, app/resources/views/pages/home.blade.php, app/resources/views/pages/location_search/spreadsheet.blade.php
Added button to the end of a search with no results that links to the add location page
=> Issue #611

app/app/Http/Controllers/ProfileController.php
Now redirects home after saving profile
=> Issue #612

app/resources/views/pages/location_search/spreadsheet.blade.php
Redirect was already implemented so I just had to change the link
=> Now redirects to add-location after signing in addresses #611

importers/utils/sync/sync.py
=> importers: adjusted sync to update location tag descriptions

importers/ableroad.com/easy_importer.py, importers/ableroad.com/generate_csv.py, importers/ableroad.com/html_scraper.py, importers/ableroad.com/model/toilet.py, importers/ableroad.com/readme_easy_importer.md
=> importers: started merging details with information from index listings

app/app/Http/Controllers/LocationSearchController.php
Addresses #651, very simple change.
=> Location search displays map first

app/app/Http/Controllers/LocationManagementController.php
This fixes a mistake introduced by pull request #661.
=> app: adjusted location delete to redirect to my locations

app/app/Http/Controllers/PasswordRecoveryController.php, app/resources/views/pages/password_recovery/email_sent.blade.php, app/resources/views/pages/password_recovery/form.blade.php, app/resources/views/pages/password_recovery/unmatched_email.blade.php, app/resources/views/pages/signin.blade.php
I wasn't able to test that it actually sends the link because I was on localhost, but it should all work.
Here is a preview of the page
=> #648, now lets users resend password verification link

app/app/Http/Controllers/PasswordRecoveryController.php, app/tests/PasswordRecoveryTest.php
Related to work on issue #648 and pull request #654
=> app: fixed broken password recovery test and code styling

app/app/Http/Controllers/PasswordRecoveryController.php
This problem was introduced by pull request #674.
This is related to changes for issue #648.
=> app: fixed code styling in PasswordRecoveryController.php

app/package-lock.json
Tracking the package-lock.json file is recommended by npm.
=> app: committed package-lock.json

app/resources/assets/sass/_home.scss, app/resources/views/pages/home.blade.php
=> app: home: adjusted SCSS to minimize scrolling

app/resources/assets/sass/_location_search.scss, app/resources/views/pages/location_search/search.blade.php
=> app: added keywords to location search

app/resources/assets/sass/_privacy_policy.scss, app/resources/assets/sass/app.scss, app/resources/views/pages/privacy_policy.blade.php
This is required to have facebook authentication work.
=> app: added a privacy policy

app/resources/assets/sass/_profile_home_address.scss, app/resources/views/pages/profile/home_address_form.blade.php
=> app: fixed bug where a lot of blank space was shown in Edge

app/app/Http/Controllers/PasswordRecoveryController.php, app/resources/views/pages/privacy_policy.blade.php
Issue fixed and  .env need to contain the following:
SEND_EMAIL_ID=____@accesslocator.com
=> Issue-734 Fixed - Load Recovery Reply To Email from .env file

app/app/Http/Controllers/LocationSearchController.php
The new rating property will be important for work on issue #734 which replaces the marker images based on rating values.
Related to #738
=> app: added rating and cleaned up other properties in location map data

app/resources/views/pages/terms_of_use.blade.php
=> app: added a Terms of Use document

app/app/Http/Controllers/LocationImageController.php, app/routes/location.php, app/tests/LocationImageTest.php
=> app: added apis for listing and getting individual image
